# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025-2026 NVIDIA Corporation

from unittest.mock import AsyncMock

import numpy as np
import pytest
from alpasim_runtime.broadcaster import MessageBroadcaster
from alpasim_runtime.services.controller_service import ControllerService
from alpasim_utils.geometry import Pose, Trajectory


def _identity_pose():
    return Pose(
        np.array([0.0, 0.0, 0.0], dtype=np.float32),
        np.array([0.0, 0.0, 0.0, 1.0], dtype=np.float32),
    )


def _pose_at(x: float):
    return Pose(
        np.array([x, 0.0, 0.0], dtype=np.float32),
        np.array([0.0, 0.0, 0.0, 1.0], dtype=np.float32),
    )


@pytest.fixture
def default_args():
    now_us = 1000000
    future_us = 1100000

    pose = _pose_at(1.0)
    trajectory = Trajectory.from_poses(
        timestamps=np.array([0], dtype=np.uint64),
        poses=[pose],
    )

    # fallback_trajectory_local_to_rig spans [now_us, future_us] so interpolation works
    fallback_trajectory_local_to_rig = Trajectory.from_poses(
        timestamps=np.array([now_us, future_us], dtype=np.uint64),
        poses=[_pose_at(1.0), _pose_at(5.0)],
    )

    args = {
        "session_uuid": "session_uuid",
        "now_us": now_us,
        "pose_local_to_rig": _pose_at(1.0),
        "rig_linear_velocity_in_rig": np.array([1.0, 0.0, 0.0]),
        "rig_angular_velocity_in_rig": np.array([0.0, 0.0, 0.0]),
        "rig_reference_trajectory_in_rig": trajectory,
        "future_us": future_us,
        "fallback_trajectory_local_to_rig": fallback_trajectory_local_to_rig,
        "force_gt": False,
    }
    return args


def test_create_run_controller_and_vehicle_request(default_args):
    # Remove fields not needed for request creation
    args_for_request = default_args.copy()
    del args_for_request["fallback_trajectory_local_to_rig"]

    request = ControllerService.create_run_controller_and_vehicle_request(
        **args_for_request
    )
    # spot check
    assert request.session_uuid == default_args["session_uuid"]
    assert request.state.timestamp_us == default_args["now_us"]


async def test_skip_controller_instance_run_controller_and_vehicle(default_args):
    """
    Check that the ControllerService in skip mode returns the fallback pose
    """
    mock_broadcaster = AsyncMock(spec=MessageBroadcaster)

    controller = ControllerService(address="localhost:50051", skip=True)

    async with controller.rollout_session(
        uuid=default_args["session_uuid"], broadcaster=mock_broadcaster
    ):
        args = default_args.copy()
        del args["session_uuid"]

        propagated_states = await controller.run_controller_and_vehicle(**args)
        assert len(propagated_states) == 1
        pose = propagated_states[-1].pose_local_to_rig
        pose_est = propagated_states[-1].pose_local_to_rig_estimate

        # The fallback trajectory interpolated at future_us should give x=5.0
        expected_pose = _pose_at(5.0)
        assert pose.vec3 == pytest.approx(expected_pose.vec3, abs=1e-4)
        assert pose.quat == pytest.approx(expected_pose.quat, abs=1e-4)
        assert pose_est.vec3 == pytest.approx(expected_pose.vec3, abs=1e-4)
        assert pose_est.quat == pytest.approx(expected_pose.quat, abs=1e-4)


async def test_skip_mode_generates_intermediates(default_args):
    """
    When pose_reporting_interval_us > 0 and the controller is in skip mode,
    intermediate states should be generated by interpolating fallback_trajectory_local_to_rig.
    """
    mock_broadcaster = AsyncMock(spec=MessageBroadcaster)

    controller = ControllerService(address="localhost:50051", skip=True)

    now_us = default_args["now_us"]
    future_us = default_args["future_us"]
    interval_us = 25000  # 25ms -> 4 intermediates expected

    async with controller.rollout_session(
        uuid=default_args["session_uuid"], broadcaster=mock_broadcaster
    ):
        args = default_args.copy()
        del args["session_uuid"]
        args["pose_reporting_interval_us"] = interval_us

        propagated_states = await controller.run_controller_and_vehicle(**args)

        expected_intermediate_timestamps = list(
            range(now_us + interval_us, future_us, interval_us)
        )
        # intermediates + 1 final state
        assert len(propagated_states) == len(expected_intermediate_timestamps) + 1

        # Check that intermediate timestamps are correct
        for i, expected_t in enumerate(expected_intermediate_timestamps):
            assert propagated_states[i].timestamp_us == expected_t

        # Final state is at future_us
        assert propagated_states[-1].timestamp_us == future_us

        # Intermediate poses should be interpolated between x=1.0 and x=5.0
        for state in propagated_states[:-1]:
            x = state.pose_local_to_rig.vec3[0]
            assert 1.0 < x < 5.0, f"Intermediate x={x} should be between 1.0 and 5.0"
