# Alpasim CI/CD pipeline.
#
# The pipeline is broken up into stages and packaces, with common.yml providing shared configurations.

variables:
  FF_TIMESTAMPS: true
  # Pipeline target determines which sub-path to use when running pipelines manually.
  PIPELINE_TARGET:
    value: "Alpasim Test"
    options:
      - "Alpasim Test"
      - "Build and test Wizard"
      - "Build and test GRPC"
      - "Build and test tools"
      - "Build and test EVAL"
      - "Build and test Runtime"
      - "Build and test DDB"

    description: "Pipeline target determines which jobs will be executed by this pipeline. Alpasim smoke runs the smoke test against your chosen branch & images. Squash files (.sqsh) are created on demand by the wizard when running on SLURM."

  ALPAMAYO_IMAGE:
    value: ""
    description: "(Optional) Override the Alpamayo image. Should be a full image path, including registry & tag."

  NRE_IMAGE:
    value: ""
    description: "(Optional) Override the NRE image. Should be a full image path, including registry & tag."

  PHYSICS_IMAGE:
    value: ""
    description: "(Optional) Override the Alpasim Physics image. Should be a full image path, including registry & tag."

  TRAFFIC_IMAGE:
    value: ""
    description: "(Optional) Override the Trafficsim image. Should be a full image path, including registry & tag."

  RUNTIME_IMAGE:
    value: ""
    description: "(Optional) Override the Alpasim Runtime image. Should be a full image path, including registry & tag."

  CONTROLLER_IMAGE:
    value: ""
    description: "(Optional) Override the Alpasim Controller image. Should be a full image path, including registry & tag."

  WIZARD_CONFIG_NAME:
    value: ""
    description: "(Optional) When running tests, use provided config yaml file, found in wizard/configs, instead of running the default smoke test. This YAML should use the run method SLURM."

  SLURM_GPU_COUNT:
    value: "1"
    options:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
    description: "(Optional) When running custom tests which require > 1 GPU, specify the GPU count here. If running a custom test which requires more than 1 GPU, you must specify the GPU count here to be provisioned the proper Slurm resources."

  KPI_IMAGE:
    value: ""
    description: "(Optional) Override the Alpasim KPI image. Should be a full image path, inclduing registry & tag."

  DDB_IMAGE:
    value: ""
    description: "(Optional) Override the DDB Indexer / Muxer image. Should be a full image path, inclduing registry & tag. If this is set on a manual pipeline, the DDB image will NOT be built, even if there are changes to it in the target branch."

  GIT_LFS_SKIP_SMUDGE: "1"

stages:
  - lint
  - build
  - test
  - publish
  - release

default:
  interruptible: true

workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    - !reference [.ignore_drafts, rules]
    - !reference [.ignore_pushes, rules]
    - when: always

include:
  - local: /plugins/internal/cicd/gitlab/definitions.yml
  - local: plugins/internal/cicd/gitlab/common.yml
  - local: plugins/internal/cicd/gitlab/prepare.yml
  - local: plugins/internal/cicd/gitlab/lint.yml
  - local: plugins/internal/cicd/gitlab/build.yml
  - local: plugins/internal/cicd/gitlab/test.yml
  - local: plugins/internal/cicd/gitlab/cleanup.yml
  - local: plugins/internal/cicd/gitlab/release.yml
